# Generated by Django 4.2.4 on 2023-09-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconnect', '0003_alter_search_options_alter_singleresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
