# Generated by Django 4.2.4 on 2023-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconnect', '0006_rename_search_save_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_search',
            name='search_dict',
            field=models.TextField(default=''),
        ),
    ]
