# Generated by Django 4.2.4 on 2023-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconnect', '0007_save_search_search_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_study',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
