# Generated by Django 4.1.7 on 2023-11-30 23:58

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiconnect', '0009_baseuser_doctoruser_hospitaluser_patientuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenterUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiconnect.baseuser')),
                ('organization_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('apiconnect.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='doctoruser',
            old_name='specialization',
            new_name='associated_organization',
        ),
        migrations.DeleteModel(
            name='HospitalUser',
        ),
    ]
