# Generated by Django 4.1.7 on 2023-12-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconnect', '0010_healthcenteruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenteruser',
            name='organization_description',
            field=models.TextField(max_length=500),
        ),
    ]
